> # **Name : Abhishek Subhash Swami**

> # **Roll No. 13**

---

# **Experiment 2 : Implementation of Universal functions in NumPy**

In [2]:
#import numpy packages

import numpy as np

## Statistical Functions

### amin
> This function is used to find the minimum value along a specified axis of an array.
```
numpy.amin(arr, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
```

In [3]:
arr1=np.random.randint(100,size=50).reshape(10,5)

print(arr1)


[[79 59 23 49 54]
 [92 82 62  7 88]
 [65  2 45 20 71]
 [18 18 58 99 96]
 [78 85 86  1 24]
 [ 3 98 31 51 74]
 [30 56 96 33 31]
 [32 53 94 77 68]
 [92 96 31 34  2]
 [37 58 30 48  1]]


In [4]:
#get minimum of all values
print(np.amin(arr1))

1


In [5]:
#get row of minimum values along each column
print(np.amin(arr1,axis=0))

[ 3  2 23  1  1]


In [6]:
#get column of minimum values along each row

print(np.amin(arr1,axis=1))

[23  7  2 18  1  3 30 32  2  1]


### amax
> This function is used to find maximum value along a specified axis of an array.
```
numpy.amax(arr, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
```

In [7]:
print(np.amax(arr1))

99


In [8]:
#get row of maximum values along each column
print(np.amax(arr1,axis=0))

[92 98 96 99 96]


In [9]:
#get column of maximum values along each row
print(np.amax(arr1,axis=1))

[79 92 71 99 86 98 96 94 96 58]


### ptp
>This function is used to find the range of values (i.e., the difference between the maximum and minimum values) along a specified axis of an array
```
numpy.ptp(arr, axis=None, out=None, keepdims=<no value>, where=<no value>)
```


In [10]:
print(np.ptp(arr1))

98


In [11]:
#get row of difference between maximum and minimum values along each column
print(np.ptp(arr1,axis=0))

[89 96 73 98 95]


In [12]:
#get column of difference between maximum and minimum values along each rows
print(np.ptp(arr1,axis=1))

[56 85 69 81 85 95 66 62 94 57]


### percentile
> This function is used to compute the q-th percentile of the data along the specified axis.

```
numpy.percentile(arr, q, axis=None, out=None, keepdims=<no value>, interpolation='linear')
```

In [13]:
#calculate 50th percentile from arr1
print(np.percentile(arr1,50))

53.5


In [14]:
#calclulate 50th percentile along vertical axis
print(np.percentile(arr1,50,axis=0))

[51.  58.5 51.5 41.  61. ]


In [15]:
#caluclate 50th percentile along horizontal axis
print(np.percentile(arr1,50,axis=1))

[54. 82. 45. 58. 78. 51. 33. 68. 34. 37.]


### mean
>This is a function in NumPy used to calculate arithmetic mean of array
```
numpy.mean(a, axis=None, dtype=None, out=None, keepdims=False)
```

In [16]:
print(np.mean(arr1))

52.34


In [17]:
# mean along vertical axis
print(np.mean(arr1,axis=0,dtype=int))

[52 60 55 41 50]


In [18]:
# mean along horizontal axis
print(np.mean(arr1,axis=1))

[52.8 66.2 40.6 57.8 54.8 51.4 49.2 64.8 51.  34.8]


### median

> This is a function in NumPy used to calculate median value of array
```
numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
```


In [19]:
print(np.median(arr1))

53.5


In [20]:
# median along vertical axis
print(np.median(arr1,axis=0))

[51.  58.5 51.5 41.  61. ]


In [21]:
# median along horizontal axis
print(np.median(arr1,axis=1))

[54. 82. 45. 58. 78. 51. 33. 68. 34. 37.]


### Standard Deviation
> This is a function in NumPy used to calculate standard deviation of array.
```
numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)
```

In [22]:
arr2=np.array([[12,23,34,45,56],[21,32,53,64,57]])
print(np.std(arr2))

16.876314763596937


In [23]:
#calculate standard deviation along vertical axis
print(np.std(arr2,axis=0))

[4.5 4.5 9.5 9.5 0.5]


In [24]:
#calculate standard deviation along horizontal axis
print(np.std(arr2,axis=1))

[15.55634919 16.20617166]


### variance

>
This is a function in NumPy used to calculate variance of array numpy.
```
var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)
```

In [25]:
print(np.var(arr2))

284.81


In [26]:
#calculate variance along vertical axis
print(np.var(arr2,axis=0))

[20.25 20.25 90.25 90.25  0.25]


In [27]:
##calculate variance along horizontal axis
print(np.var(arr2,axis=1))

[242.   262.64]


### Average
> This is a NumPy function used to calculate weighted arithmetic mean of array

```
numpy.average(a, axis=None, weights=None, returned=False)
```

In [28]:
weights=np.array([5,4,3,2,1])
arr3=np.array([1,2,3,4,5])
print(np.average(arr3,weights=weights))

2.3333333333333335


## Trigonometric Functions

### Sine Cosine Tangent
> NumPy provides several trigonometric functions that can be used to calculate the sine, cosine, and tangent of angles in radians.

* np.sin(): This function returns the sine of an angle.

* np.cos(): This function returns the cosine of an angle.

* np.tan(): This function returns the tangent of an angle.

In [29]:
angle=float(input("Enter angle in degrees : "))
rad=angle*(np.pi/180)

Enter angle in degrees : 60


In [30]:
# sin ()
print(round(np.sin(rad),4))

0.866


In [31]:
# cos ()
print(round(np.cos(rad),4))

0.5


In [32]:
# tan ()
print(round(np.tan(rad),4))

1.7321


### arcsin arccos arctan

>NumPy provides three trigonometric functions that compute the inverse of the sine, cosine, and tangent functions, respectively. These functions are:

* ```arcsin(x)``` - Computes the inverse sine (in radians) of the input element-wise.
* ```arccos(x)``` - Computes the inverse cosine (in radians) of the input element-wise.
* ```arctan(x)``` - Computes the inverse tangent (in radians) of the input element-wise.

In [33]:
vals=np.array([0,0.5,1/np.sqrt(2),1])
vals

array([0.        , 0.5       , 0.70710678, 1.        ])

In [34]:
#arcsin
print(np.arcsin(vals))                #gives an array of angles in radians
print(np.arcsin(vals)*(180/np.pi))    #gives an array of angles in degrees

[0.         0.52359878 0.78539816 1.57079633]
[ 0. 30. 45. 90.]


In [35]:
#arccos
print(np.arccos(vals))                #gives an array of angles in radians
print(np.arccos(vals)*(180/np.pi))    #gives an array of angles in degrees

[1.57079633 1.04719755 0.78539816 0.        ]
[90. 60. 45.  0.]


In [39]:
#arctan
print(np.arctan(vals))                #gives an array of angles in radians
print(np.arctan(vals)*(180/np.pi))    #gives an array of angles in degrees

[0.         0.46364761 0.61547971 0.78539816]
[ 0.         26.56505118 35.26438968 45.        ]


### hypot
>This is a NumPy function that returns the hypotenuse of a right-angled triangle with sides x and y, given by the Pythagorean theorem. It computes the Euclidean distance between the origin and the point (x, y) in a 2D coordinate system. Mathematically, np.hypot(x, y) returns the value of sqrt(x^2 + y^2) for each corresponding element in the input arrays.
```
np.hypot(x, y)
```

In [41]:
#find hypotenuse of triangles with side 3 and 4
print(np.hypot(5,12))

13.0


In [48]:
#find hypotenuse of triangles with array of side
sides1=np.array([3,5,6,9,15])
sides2=np.array([4,12,8,12,20])
print(np.hypot(sides1,sides2))

[ 5. 13. 10. 15. 25.]


### sinh cosh tanh
>NumPy provides three hyperbolic trigonometric functions that compute the hyperbolic sine, cosine, and tangent functions, respectively. These functions are:

* ```np.sinh(x)``` - Computes the hyperbolic sine of the input element-wise.
* ```np.cosh(x)``` - Computes the hyperbolic cosine of the input element-wise.
* ```np.tanh(x)``` - Computes the hyperbolic tangent of the input element-wise.

In [49]:
a=np.array([1,2,3])
#find hyperbolic sine value of a
print(np.sinh(a))

[ 1.17520119  3.62686041 10.01787493]


In [50]:
#find hyperbolic cosine value of a
print(np.cosh(a))

[ 1.54308063  3.76219569 10.067662  ]


In [51]:
#find hyperbolic tangent value of a
print(np.tanh(a))

[0.76159416 0.96402758 0.99505475]


### Angle Conversion

> ```np.deg2rad(x)``` - Converts angles from degrees to radians.

> ```np.rad2deg(x)``` - Converts angles from radians to degrees.

In [52]:
d=np.array([0,30,45,60,90,120,180,270,360])
#convert degree to radian
print(np.deg2rad(d))

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265 4.71238898 6.28318531]


In [54]:
r=np.array([0,0.5,0.9,1,1.5,2,np.pi,4.7,2*np.pi])
#convert radian to degree
print(np.rad2deg(r))

[  0.          28.64788976  51.56620156  57.29577951  85.94366927
 114.59155903 180.         269.29016371 360.        ]


### Bit Twiddling Functions

>NumPy provides several bit twiddling functions that operate on arrays of binary numbers. These functions include:

* `np.bitwise_and(x1, x2)` - Computes the bitwise AND of two input arrays element-wise.
* `np.bitwise_or(x1, x2)` - Computes the bitwise OR of two input arrays element-wise.
* `np.bitwise_xor(x1, x2)` - Computes the bitwise XOR of two input arrays element-wise.
* `np.invert(x)` - Computes the bitwise NOT of an input array element-wise.
* `np.left_shift(x, shift)` - Shifts the bits of an input array to the left by a specified number of positions.
* `np.right_shift(x, shift)` - Shifts the bits of an input array to the right by a specified number of positions.

>All of these functions take one or two input arrays and return an array of the same shape as the input array(s).

In [60]:
a=np.array([1,2,3,4,5],dtype=np.uint8)
b=np.array([1,2,1,3,6],dtype=np.uint8)

In [61]:
#bitwise_and
print(np.bitwise_and(a,b))

[1 2 1 0 4]


In [62]:
#bitwise_or
print(np.bitwise_or(a,b))

[1 2 3 7 7]


In [63]:
#bitwise_xor
print(np.bitwise_xor(a,b))

[0 0 2 7 3]


In [64]:
#invert
print(np.invert(a))

[254 253 252 251 250]
